; WROOM Hub — Master controller for Cabane Marcoux
; Reads: dompeur (limit switch), bassin 1 (JSN-SR04T)
; Scans BLE: CBM (bassin 2+3), Inkbird (temp/hum)
; Publishes: MQTT + BLE advertise "CBM-HUB"

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM6
monitor_port = COM6
lib_deps =
    h2zero/NimBLE-Arduino@^1.4.1
    knolleary/PubSubClient@^2.8
build_flags =
    -D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
